if(NOT _PROJECT_CONFIG_ROOT)
  get_filename_component(_PROJECT_CONFIG_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()

function(read_config VAR_NAME)
  if(NOT _PROJECT_CONFIG_JSON)
    file(READ "${_PROJECT_CONFIG_ROOT}/project-config.json" _PROJECT_CONFIG_JSON)
    if("${_PROJECT_CONFIG_JSON}" STREQUAL "")
      message(FATAL_ERROR "project-config.json is empty or missing. "
        "Create it at ${_PROJECT_CONFIG_ROOT}/project-config.json "
        "using project-config.schema.json as a guide.")
    endif()
  endif()

  set(_PATH "")
  foreach(_KEY ${ARGN})
    list(APPEND _PATH "${_KEY}")
  endforeach()

  string(JSON _VAL ERROR_VARIABLE _ERR GET "${_PROJECT_CONFIG_JSON}" ${_PATH})
  if(NOT "${_ERR}" STREQUAL "NOTFOUND")
    message(FATAL_ERROR "project-config.json is missing '${_PATH}'. "
      "See project-config.schema.json for required values.")
  endif()

  set("${VAR_NAME}" "${_VAL}" PARENT_SCOPE)
endfunction()

read_config(PROJECT_CONFIG_NAME product name)
read_config(PROJECT_CONFIG_COMPANY product companyName)
read_config(PROJECT_CONFIG_YEAR product copyrightYear)
read_config(PROJECT_CONFIG_VERSION_STR version string)
read_config(PROJECT_CONFIG_NAMESPACE identifiers namespace)
read_config(PROJECT_CONFIG_BUNDLE_ID identifiers bundleId)
read_config(PROJECT_CONFIG_MFR_CODE identifiers plugin manufacturerCode)
read_config(PROJECT_CONFIG_PLUGIN_CODE identifiers plugin pluginCode)
read_config(PROJECT_CONFIG_CLASS_PREFIX identifiers classPrefix)
read_config(PROJECT_CONFIG_APPDATA_DIR paths appdataDirName)
read_config(PROJECT_CONFIG_SOURCE_PREF_FILENAME paths sourcePreferenceFilename)
read_config(PROJECT_CONFIG_ENTITLEMENT_FILENAME paths entitlementFilename)
read_config(PROJECT_CONFIG_DEV_SERVER_URL urls devServer)
read_config(PROJECT_CONFIG_API_URL urls productionApi)
read_config(PROJECT_CONFIG_WEBVIEW2_MISSING ui errorMessageTemplates webview2Missing)
read_config(PROJECT_CONFIG_RESOURCE_MISSING ui errorMessageTemplates resourceMissing)
read_config(PROJECT_CONFIG_TOKEN_TYPE_V1 tokens entitlementV1)
read_config(PROJECT_CONFIG_PLUGIN_TARGET build pluginTargetName)
read_config(PROJECT_CONFIG_VST3_TARGET build vst3TargetName)
read_config(PROJECT_CONFIG_STANDALONE_TARGET build standaloneTargetName)
read_config(PROJECT_CONFIG_TEST_TARGET build testTargetName)
read_config(PROJECT_CONFIG_WEB_BUNDLE_TARGET build webBundleTargetName)
read_config(PROJECT_CONFIG_WEB_BUNDLE_NS build webBundleNamespace)
read_config(PROJECT_CONFIG_ARTEFACTS_DIR build artefactsDirName)
read_config(PROJECT_CONFIG_ENV_PREFIX env envVarPrefix)
read_config(PROJECT_CONFIG_DEV_SERVER_VAR env devServerVar)
read_config(PROJECT_CONFIG_RELEASE_BUILD_VAR env releaseBuildVar)

if(PROJECT_CONFIG_NAME STREQUAL "")
  message(FATAL_ERROR "PROJECT_CONFIG_NAME (product.name) must not be empty")
endif()
if(PROJECT_CONFIG_COMPANY STREQUAL "")
  message(FATAL_ERROR "PROJECT_CONFIG_COMPANY (product.companyName) must not be empty")
endif()
if(PROJECT_CONFIG_VERSION_STR STREQUAL "")
  message(FATAL_ERROR "PROJECT_CONFIG_VERSION_STR (version.string) must not be empty")
endif()
if(NOT PROJECT_CONFIG_VERSION_STR MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+$")
  message(FATAL_ERROR "PROJECT_CONFIG_VERSION_STR '${PROJECT_CONFIG_VERSION_STR}' "
    "must be semver (e.g. 0.1.0). Got: '${PROJECT_CONFIG_VERSION_STR}'")
endif()
string(LENGTH "${PROJECT_CONFIG_MFR_CODE}" _MFR_LEN)
if(NOT _MFR_LEN EQUAL 4)
  message(FATAL_ERROR "PROJECT_CONFIG_MFR_CODE '${PROJECT_CONFIG_MFR_CODE}' "
    "must be exactly 4 alphanumeric characters")
endif()
string(LENGTH "${PROJECT_CONFIG_PLUGIN_CODE}" _PLUGIN_LEN)
if(NOT _PLUGIN_LEN EQUAL 4)
  message(FATAL_ERROR "PROJECT_CONFIG_PLUGIN_CODE '${PROJECT_CONFIG_PLUGIN_CODE}' "
    "must be exactly 4 alphanumeric characters")
endif()

if(NOT _schema_version_checked)
  file(READ "${_PROJECT_CONFIG_ROOT}/project-config.schema.json" _SCHEMA_JSON)
  string(JSON _SCHEMA_VERSION ERROR_VARIABLE _SV_ERR GET "${_SCHEMA_JSON}" "$version")
  if(NOT "${_SV_ERR}" STREQUAL "NOTFOUND")
    message(FATAL_ERROR "project-config.schema.json is missing '$version' field. "
      "Schema version tracking is required per CFG-08.")
  endif()
  set(_EXPECTED_SCHEMA_VERSION "1.0.0")
  if(NOT "${_SCHEMA_VERSION}" STREQUAL "${_EXPECTED_SCHEMA_VERSION}")
    message(FATAL_ERROR "project-config.schema.json $version mismatch. "
      "Expected: ${_EXPECTED_SCHEMA_VERSION}, Found: ${_SCHEMA_VERSION}. "
      "Update Config.cmake _EXPECTED_SCHEMA_VERSION or revert schema $version.")
  endif()
  set(_schema_version_checked TRUE)
endif()

message(STATUS "Config: ${PROJECT_CONFIG_NAME} ${PROJECT_CONFIG_VERSION_STR} (${PROJECT_CONFIG_COMPANY})")
